apiVersion: batch/v1
kind: CronJob
metadata:
  name: model-prune
spec:
  concurrencyPolicy: Forbid
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          terminationGracePeriodSeconds: 0
          restartPolicy: Never
          containers:
            - name: cronjob
              imagePullPolicy: IfNotPresent
              image: {{ .Values.image.name }}
              command:
                - php
                - artisan
                - model:prune
                - --model='Domain\MagicLink\Models\MagicLink'
              envFrom:
                - secretRef:
                    name: {{ .Values.labels.app }}
