apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name | default "backend-themembers"}}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class | default "alb" }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ConfigMap.CERTIFICATE_ARN | default "themembers" }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme | default "internet-facing" }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.group_name | default "themembers" }}
    alb.ingress.kubernetes.io/healthcheck-protocol: {{ .Values.ingress.healthcheck_protocol | default "HTTP" }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.ingress.healthcheck_path | default "/ht" }}
    alb.ingress.kubernetes.io/healthcheck-port: "{{ default 80 .Values.ingress.healthcheck_port }}"
    alb.ingress.kubernetes.io/healthy-threshold-count: "{{default 3 .Values.ingress.healthy_threshold_count }}"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "{{default 2 .Values.ingress.unhealthy_threshold_count }}"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "{{default 15 .Values.ingress.timeout_seconds }}"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "{{default 45 .Values.ingress.interval_seconds }}"
    alb.ingress.kubernetes.io/success-codes: "{{ default 200 .Values.ingress.success_codes }}"
    # alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.waf_arn | default "wefewfwefewffwef" }}


spec:
  rules:
    - host: {{ .Values.ingress.host | default "wefwefwef"}}
      http:
        paths:
         - path: {{ .Values.ingress.path | default "/" }}
           pathType: {{ .Values.ingress.pathType | default "Prefix" }}
           backend:
             service:
              name: {{ .Values.labels.service | default "backend-app-service"}}
              port:
                number: {{ .Values.service.port | default 80}}
